# Shikakun Bot!!
# Created by RubyMine.
# User: axlyody

require 'rubygems'
require 'discordrb'
require 'yaml'
require 'uri'
require_relative 'lib/moonkaini'

config = YAML.load_file('config.yaml')

bot = Discordrb::Commands::CommandBot.new token: config['token'], client_id: config['client_id'], prefix: '.', advanced_functionality: true, help_command: 'shikakun'
moonkaini = Moonkaini.new

bot.ready do
  bot.game = '.ask_shikakun for help'
end


# moonkaini.co
bot.command :vn, description:'Get the visual novel information including download link itself' do |event, action, *args|
  case action
    when 'list'
      getobject = moonkaini.findby_letter(args.join(' '))
      event.channel.send_embed do |embed|
        embed.author = Discordrb::Webhooks::EmbedAuthor.new(name:'Request from '+event.user.name, icon_url:  event.user.avatar_url)
        embed.title = 'Results for "'+args.join(' ')+'"'
        embed.description = getobject
        embed.colour = "#009688"
        embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
      end
    when "get"
      getobject = moonkaini.findby_vn(args.join(' '))
      event.channel.send_embed do |embed|
        if getobject[1] == 'Unknown'
          embed.colour = '#f44336'
          embed.title = 'Hmmm...'
          embed.description = '"'+args.join(' ')+'" was not found.'
          embed.image = Discordrb::Webhooks::EmbedImage.new(url: 'https://moonkaini.co/ui/images/toa1.png')
          embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
        else
          if getobject[6] == 'Unknown'
            embed.title = getobject[0]
            embed.description = 'No specific information for this vn due limitation data that we got using VNDB API.'
            embed.add_field(name: 'Download', value: getobject[5], inline: false)
            embed.add_field(name: 'Link', value: '[Download]('+ getobject[5] +') - [Check on VNDB](https://vndb.org/v/all?sq='+ URI.encode(getobject[5]) +')', inline: false)
            embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
          else
            embed.title = getobject[0]
            if getobject[3]
              embed.description = getobject[3]
            end
            if getobject[6]
              embed.image = Discordrb::Webhooks::EmbedImage.new(url: 'https://'+getobject[6])
            end
            if getobject[2]
              embed.add_field(name: 'Original', value: getobject[2], inline: true)
            end
            if getobject[4]
              embed.add_field(name: 'Released', value: getobject[4], inline: true)
            end
            if getobject[7]
              embed.add_field(name: 'Developer', value: getobject[7], inline: true)
            end
            if getobject[5]
              embed.add_field(name: 'Link', value: '[Download]('+ getobject[5] +') - [Check on VNDB](https://vndb.org/v/all?sq='+ URI.encode(getobject[5]) +')', inline: false)
            end

            embed.colour = "#6689d6"
            embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
          end
        end
      end
    when 'new'
      getobject = moonkaini.this_month()
      event.channel.send_embed do |embed|
        embed.author = Discordrb::Webhooks::EmbedAuthor.new(name: 'Request from '+event.user.name, icon_url: event.user.avatar_url)
        embed.title = 'This Month'
        embed.description = getobject
        embed.colour = "#ffc107"
        embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
      end
    else
      event.channel.send_embed do |embed|
        embed.colour = '#f44336'
        embed.title = 'Wrong command'
        embed.description = '**List of available commands**

.ask_shikakun : Provide a list commands available
.vn get [title] : Get the visual novel information including download link itself Ex ".vn get Wagamama"
.vn list [query] : List of available data on the database. Ex ".vn list Wa"
.vn new : New releases this month
     '
        embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
      end
  end
end

bot.command :ask_shikakun do |event|
  event.channel.send_embed message = 'Getting help with commands' do |embed|
    embed.title = 'Shikakun Bot!! Ruby ver.'
    embed.description = '
.ask_shikakun : Provide a list commands available
.vn get [title] : Get the visual novel information including download link itself Ex ".vn get Wagamama"
.vn list [query] : List of available data on the database. Ex ".vn list Wa"
.vn new : New releases this month
     '
    embed.footer = Discordrb::Webhooks::EmbedFooter.new(text: 'Generated by Moonkaini.co', icon_url: 'https://moonkaini.co/ui/images/toa1.png')
  end
end

bot.run
